import { Coffee } from "@/app/lib/definitions/coffee-definitions";

const calculatePriceFor1kg = (priceFor250g: number): number => {
  return Math.round(priceFor250g * 4 * 0.9);
};

export const coffeeCodesMappings: Record<string, string> = {
  C0001: "Ethiopia Yirgacheffe",
  C0002: "Colombia Huila Supremo",
  C0003: "Guatemala Antigua",
  C0004: "Kenya AA Nyeri",
  C0005: "Sumatra Mandheling",
  C0006: "Brazil Santos",
  C0007: "Honduras Marcala Organic",
  C0008: "Panama Geisha",
  C0009: "Espresso Harmony Blend",
  C0010: "Tanzania Peaberry",
  C0011: "Ethiopia Sidamo",
  C0012: "Nicaragua Decaf (Filter)",
  C0013: "Costa Rica Tarrazú",
  C0014: "Mexico Chiapas Decaf (Filter)",
  C0015: "Peru Cajamarca Decaf (Espresso)",
};

export const grindSizeCodeMappings: Record<string, string> = {
  G01: "Whole beans",
  G02: "Chemex",
  G03: "V60",
  G04: "Espresso",
  G05: "French press",
  G06: "Moka pot",
};

export const specialtyCoffees: Coffee[] = [
  {
    id: "38ed1c67-bd76-4f4d-a4cc-3925b546c713",
    productCode: "C0001",
    name: "Ethiopia Yirgacheffe",
    description:
      "A floral and citrusy coffee from the Yirgacheffe region, " +
      "offering notes of jasmine and bright acidity. " +
      "Perfect for filter brewing.",
    originType: "single origin",
    singleOriginName: "Ethiopia, Yirgacheffe, Aricha Estate",
    beanType: "arabica",
    roastingLocation: "Seattle, USA",
    brewMethod: "filter",
    roastLevel: "light",
    roastLevelDetail: "cinnamon",
    processingMethod: "washed",
    isDecaf: false,
    primaryFlavors: ["floral", "citrus", "jasmine"],
    body: "light",
    acidity: "high",
    priceFor250g: 1599,
    priceFor1kg: calculatePriceFor1kg(1599),
  },
  {
    id: "a4519867-6b38-4c5a-8fcf-f1ea3e9b10c9",
    productCode: "C0002",
    name: "Colombia Huila Supremo",
    description:
      "Rich and smooth, this Colombian coffee offers notes of chocolate, " +
      "caramel, and red apple, with medium acidity and a balanced body.",
    originType: "single origin",
    singleOriginName: "Colombia, Huila, La Pradera Estate",
    beanType: "arabica",
    roastingLocation: "Bogotá, Colombia",
    brewMethod: "espresso",
    roastLevel: "medium",
    roastLevelDetail: "city",
    processingMethod: "washed",
    isDecaf: false,
    primaryFlavors: ["chocolate", "caramel", "red apple"],
    body: "medium",
    acidity: "medium",
    priceFor250g: 1499,
    priceFor1kg: calculatePriceFor1kg(1499),
  },
  {
    id: "f6cbd4dc-e9e8-4b63-9d45-9b725a682ce6",
    productCode: "C0003",
    name: "Guatemala Antigua",
    description:
      "From the Antigua region, " +
      "this coffee features bright cherry, cocoa, and nutmeg notes. " +
      "A perfect choice for balanced, flavorful brews.",
    originType: "single origin",
    singleOriginName: "Guatemala, Antigua, Finca Medina",
    beanType: "arabica",
    roastingLocation: "Antigua, Guatemala",
    brewMethod: "filter",
    roastLevel: "medium light",
    roastLevelDetail: "new england",
    processingMethod: "washed",
    isDecaf: false,
    primaryFlavors: ["cherry", "cocoa", "nutmeg"],
    body: "medium",
    acidity: "medium",
    priceFor250g: 1399,
    priceFor1kg: calculatePriceFor1kg(1399),
  },
  {
    id: "1c71639b-bbfa-4c7b-91e3-91c8f4de758b",
    productCode: "C0004",
    name: "Kenya AA Nyeri",
    description:
      "A bold and fruity coffee from Nyeri " +
      "with notes of blackcurrant, grapefruit, and brown sugar. " +
      "Bright acidity and a clean finish.",
    originType: "single origin",
    singleOriginName: "Kenya, Nyeri, Gachatha Cooperative",
    beanType: "arabica",
    roastingLocation: "Nairobi, Kenya",
    brewMethod: "filter",
    roastLevel: "medium",
    roastLevelDetail: "city",
    processingMethod: "washed",
    isDecaf: false,
    primaryFlavors: ["blackcurrant", "grapefruit", "brown sugar"],
    body: "light",
    acidity: "high",
    priceFor250g: 1799,
    priceFor1kg: calculatePriceFor1kg(1799),
  },
  {
    id: "04f9e1c2-7097-45a0-a24e-5fc48bd6d589",
    productCode: "C0005",
    name: "Sumatra Mandheling",
    description:
      "Earthy and bold, with spicy dark chocolate notes. " +
      "This wet-hulled coffee from Sumatra is perfect for espresso " +
      "or full-bodied brews.",
    originType: "single origin",
    singleOriginName: "Indonesia, Sumatra",
    beanType: "arabica",
    roastingLocation: "Jakarta, Indonesia",
    brewMethod: "espresso",
    roastLevel: "medium dark",
    roastLevelDetail: "full city",
    processingMethod: "wet-hulled",
    isDecaf: false,
    primaryFlavors: ["earthy", "spicy", "dark chocolate"],
    body: "full",
    acidity: "light",
    priceFor250g: 1499,
    priceFor1kg: calculatePriceFor1kg(1499),
  },
  {
    id: "c5a9c05d-3b95-481b-b5ff-4e2b705ecf82",
    productCode: "C0006",
    name: "Brazil Santos",
    description:
      "A smooth, nutty coffee " +
      "with peanut, milk chocolate, and caramel flavors. " +
      "Great for espresso or all-day drinking.",
    originType: "single origin",
    singleOriginName: "Brazil, Santos",
    beanType: "arabica",
    roastingLocation: "São Paulo, Brazil",
    brewMethod: "espresso",
    roastLevel: "medium",
    roastLevelDetail: "city",
    processingMethod: "natural",
    isDecaf: false,
    primaryFlavors: ["peanut", "milk chocolate", "caramel"],
    body: "medium",
    acidity: "light",
    priceFor250g: 1299,
    priceFor1kg: calculatePriceFor1kg(1299),
  },
  {
    id: "42688af2-8bcd-47a3-b8f0-90258f7d86e5",
    productCode: "C0007",
    name: "Honduras Marcala Organic",
    description:
      "Tropical fruit, honey, and almond notes " +
      "define this organic coffee from Honduras. " +
      "Sweet and balanced with medium body.",
    originType: "single origin",
    singleOriginName: "Honduras, Marcala",
    beanType: "arabica",
    roastingLocation: "Tegucigalpa, Honduras",
    brewMethod: "filter",
    roastLevel: "medium light",
    roastLevelDetail: "new england",
    processingMethod: "honey",
    isDecaf: false,
    primaryFlavors: ["tropical fruit", "honey", "almond"],
    body: "medium",
    acidity: "medium",
    priceFor250g: 1499,
    priceFor1kg: calculatePriceFor1kg(1499),
  },
  {
    id: "b3ec2e65-8177-46a8-bc5e-e7a6b274a963",
    productCode: "C0008",
    name: "Panama Geisha",
    description:
      "Luxurious and rare, this Panama Geisha offers jasmine, " +
      "bergamot, and peach notes. Bright and floral with high acidity.",
    originType: "single origin",
    singleOriginName: "Panama, Boquete, Hacienda La Esmeralda",
    beanType: "arabica",
    roastingLocation: "Boquete, Panama",
    brewMethod: "filter",
    roastLevel: "light",
    roastLevelDetail: "cinnamon",
    processingMethod: "washed",
    isDecaf: false,
    primaryFlavors: ["jasmine", "bergamot", "peach"],
    body: "light",
    acidity: "high",
    priceFor250g: 4999,
    priceFor1kg: calculatePriceFor1kg(4999),
  },
  {
    id: "75927cfa-d8f1-4664-a6df-00e8e2ac8957",
    productCode: "C0009",
    name: "Espresso Harmony Blend",
    description:
      "A bold blend of 80% Arabica and 20% Robusta, " +
      "roasted to perfection in Naples. Notes of dark chocolate, hazelnut, " +
      "and spice make it perfect for espresso lovers.",
    originType: "blend",
    beanType: "arabica-robusta mix",
    blendRatio: "80% Arabica, 20% Robusta",
    roastingLocation: "Naples, Italy",
    brewMethod: "espresso",
    roastLevel: "medium dark",
    roastLevelDetail: "full city",
    processingMethod: "natural",
    isDecaf: false,
    primaryFlavors: ["dark chocolate", "hazelnut", "spice"],
    body: "full",
    acidity: "light",
    priceFor250g: 1399,
    priceFor1kg: calculatePriceFor1kg(1399),
  },
  {
    id: "a9bf46dc-70f3-4c0a-9c90-78ea58c8a60e",
    productCode: "C0010",
    name: "Tanzania Peaberry",
    description:
      "A rare coffee with vibrant citrus, black tea, " +
      "and pineapple notes. Grown on the slopes of Kilimanjaro " +
      "and perfect for bright, flavorful brews.",
    originType: "single origin",
    singleOriginName: "Tanzania, Kilimanjaro",
    beanType: "arabica",
    roastingLocation: "Arusha, Tanzania",
    brewMethod: "filter",
    roastLevel: "medium light",
    roastLevelDetail: "new england",
    processingMethod: "washed",
    isDecaf: false,
    primaryFlavors: ["citrus", "black tea", "pineapple"],
    body: "light",
    acidity: "high",
    priceFor250g: 1799,
    priceFor1kg: calculatePriceFor1kg(1799),
  },
  {
    id: "e034cf9c-3b79-4f20-a9ea-efcb7d6d4694",
    productCode: "C0011",
    name: "Ethiopia Sidamo",
    description:
      "Blueberry, floral, and honey flavors make this natural-processed " +
      "Ethiopian coffee a favorite. Its bright acidity and light body " +
      "shine in filter brews.",
    originType: "single origin",
    singleOriginName: "Ethiopia, Sidamo",
    beanType: "arabica",
    roastingLocation: "Addis Ababa, Ethiopia",
    brewMethod: "filter",
    roastLevel: "light",
    roastLevelDetail: "cinnamon",
    processingMethod: "natural",
    isDecaf: false,
    primaryFlavors: ["blueberry", "floral", "honey"],
    body: "light",
    acidity: "high",
    priceFor250g: 1599,
    priceFor1kg: calculatePriceFor1kg(1599),
  },
  {
    id: "1a9249a2-b563-497d-9af7-550ed97c640e",
    productCode: "C0012",
    name: "Nicaragua Decaf (Filter)",
    description:
      "A smooth, decaffeinated coffee with notes of caramel, " +
      "chocolate, and almond. Sourced from Matagalpa and perfect " +
      "for late-night sipping.",
    originType: "single origin",
    singleOriginName: "Nicaragua, Matagalpa",
    beanType: "arabica",
    roastingLocation: "Managua, Nicaragua",
    brewMethod: "filter",
    roastLevel: "medium",
    roastLevelDetail: "city",
    processingMethod: "washed",
    isDecaf: true,
    primaryFlavors: ["caramel", "chocolate", "almond"],
    body: "medium",
    acidity: "medium",
    priceFor250g: 1399,
    priceFor1kg: calculatePriceFor1kg(1399),
  },
  {
    id: "d4179bf1-680b-40d1-9c6d-bc95b1d6e6d1",
    productCode: "C0013",
    name: "Costa Rica Tarrazú",
    description:
      "From Costa Rica's Tarrazú region, this honey-processed coffee " +
      "offers bright orange, honey, and milk chocolate notes " +
      "with medium acidity.",
    originType: "single origin",
    singleOriginName: "Costa Rica, Tarrazú",
    beanType: "arabica",
    roastingLocation: "San José, Costa Rica",
    brewMethod: "filter",
    roastLevel: "medium light",
    roastLevelDetail: "new england",
    processingMethod: "honey",
    isDecaf: false,
    primaryFlavors: ["orange", "honey", "milk chocolate"],
    body: "medium",
    acidity: "medium",
    priceFor250g: 1499,
    priceFor1kg: calculatePriceFor1kg(1499),
  },
  {
    id: "1f2e68d3-7c5b-4b1c-a5b7-1d0a0f3c6174",
    productCode: "C0014",
    name: "Mexico Chiapas Decaf (Filter)",
    description:
      "A decaffeinated coffee with chocolate, brown sugar, " +
      "and citrus notes. Grown at Finca Nueva Esperanza, " +
      "this cup is smooth and flavorful.",
    originType: "single origin",
    singleOriginName: "Mexico, Chiapas, Finca Nueva Esperanza",
    beanType: "arabica",
    roastingLocation: "Mexico City, Mexico",
    brewMethod: "filter",
    roastLevel: "medium light",
    roastLevelDetail: "new england",
    processingMethod: "washed",
    isDecaf: true,
    primaryFlavors: ["chocolate", "brown sugar", "citrus"],
    body: "medium",
    acidity: "light",
    priceFor250g: 1299,
    priceFor1kg: calculatePriceFor1kg(1299),
  },
  {
    id: "6c9f0b5b-456e-4aa8-8f93-08f871abe639",
    productCode: "C0015",
    name: "Peru Cajamarca Decaf (Espresso)",
    description:
      "Dark chocolate, toffee, and almond notes shine " +
      "in this decaffeinated coffee from Peru's Cajamarca region. " +
      "Smooth and full-bodied.",
    originType: "single origin",
    singleOriginName: "Peru, Cajamarca, Cooperative Cenfrocafe",
    beanType: "arabica",
    roastingLocation: "Lima, Peru",
    brewMethod: "espresso",
    roastLevel: "medium",
    roastLevelDetail: "city",
    processingMethod: "washed",
    isDecaf: true,
    primaryFlavors: ["dark chocolate", "toffee", "almond"],
    body: "full",
    acidity: "medium",
    priceFor250g: 1399,
    priceFor1kg: calculatePriceFor1kg(1399),
  },
];
